name: Build Container Image
on:
  push:
    branches: [ main ] # If your main branch is called 'master', change 'main' to 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/opportunity-hub-ready:latest .
          docker push ghcr.io/${{ github.repository_owner }}/opportunity-hub-ready:latest
